// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ql5P6jcGtYGVIi2_zgsKrRVPxjH7diE',
    appId: '1:950629376783:web:836f50805e700d5768d47a',
    messagingSenderId: '950629376783',
    projectId: 'likeapp-adff4',
    authDomain: 'likeapp-adff4.firebaseapp.com',
    storageBucket: 'likeapp-adff4.appspot.com',
    measurementId: 'G-1BMKB09G70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD-T-kPXIOpEKBZ4e9AAzFTw98SE0ofN4',
    appId: '1:950629376783:android:9bf4ce87473e66ce68d47a',
    messagingSenderId: '950629376783',
    projectId: 'likeapp-adff4',
    storageBucket: 'likeapp-adff4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcxmBwSloIGOQUm1vJ9jr7uO6R3j3DM1I',
    appId: '1:950629376783:ios:f15353ac89d0bdee68d47a',
    messagingSenderId: '950629376783',
    projectId: 'likeapp-adff4',
    storageBucket: 'likeapp-adff4.appspot.com',
    iosBundleId: 'com.like.likeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcxmBwSloIGOQUm1vJ9jr7uO6R3j3DM1I',
    appId: '1:950629376783:ios:33595da75ec47ea768d47a',
    messagingSenderId: '950629376783',
    projectId: 'likeapp-adff4',
    storageBucket: 'likeapp-adff4.appspot.com',
    iosBundleId: 'com.example.likeApp.RunnerTests',
  );
}
